name: Python CI

on: push
jobs:
  start_linter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          pip install pytest
          poetry install
          pip install flake8
          poetry add pytest
          pip install pytest-cov
      - name: Run linter
        run: |
          poetry build
          make install
          make lint
          make tests
          pytest --cov
      - name: climate coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
         CC_TEST_REPORTER_ID: 48662e20951ddcc6cf6e6ef2b86184e2b7d9d7350cee6c003302aba7175e9499
        with:
         coverageCommand: poetry run pytest --cov=gendiff --cov-report xml
         debug: true